name: pythonapplication ci/cd pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
   
   runs-on: ubuntu-latest

    steps:
     #checkout your repository code

     -name: Checkout repository
      uses: actions/checkout@v3
     #2 setup python environment
     -name: set up python 3.10
      uses: actions/setup-python@v4
      with:
      python-version: '3.10'
     #3 Install application dependecies
     -name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
     #4 Build Docker image 
      - name: Build Docker image 
        run: |
          docker build . --file Dockerfile --tag my-flask-app:latest 
